### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by ysmr0001** [ysmr0001/chat-space#11]
# IPアドレス
52.198.157.60

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・ログアウトボタンが2つある
[![Screenshot from Gyazo](https://gyazo.com/34ab67dd13f6a7a987d71efaa6e8de61/raw)](https://gyazo.com/34ab67dd13f6a7a987d71efaa6e8de61)

その他はとてもキレイでした！

修正完了次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
